apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask1-deployment
  labels:
    app: flask1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask1
  template:
    metadata:
      labels:
        app: flask1
    spec:
      containers:
      - name: flask1
        image: SED_FOR_TAGGED_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: 'THIS_STRING_IS_REPLACED_EVERY_RUN'
